version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Kuala_Lumpur
      - POSTGRES_DB=gorm
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
  adminer:
    image: 'dockette/adminer'
    ports:
      - 8081:80  